// Generated by scripts/generate-video-posters.mjs. Do not edit by hand.
//
// Maps each clip in public/videos to its extracted poster frame and its
// measured length. AutoVideo looks a video up here when no explicit poster is
// passed, so a clip with no entry behaves exactly as it did before posters
// existed rather than requesting an image that isn't there.
export type VideoAsset = { poster: string; duration: string }

export const VIDEO_ASSETS: Record<string, VideoAsset> = {
  "/videos/ai-campaign-ad.mp4": { poster: "/images/video-posters/ai-campaign-ad.webp", duration: "PT26S" },
  "/videos/no-address.mp4": { poster: "/images/video-posters/no-address.webp", duration: "PT15S" },
  "/videos/raz-showreel-2.mp4": { poster: "/images/video-posters/raz-showreel-2.webp", duration: "PT3S" },
  "/videos/raz-showreel-4.mp4": { poster: "/images/video-posters/raz-showreel-4.webp", duration: "PT15S" },
  "/videos/raz-showreel-5.mp4": { poster: "/images/video-posters/raz-showreel-5.webp", duration: "PT7S" },
  "/videos/raz-showreel-7.mp4": { poster: "/images/video-posters/raz-showreel-7.webp", duration: "PT15S" },
  "/videos/raz-showreel.mp4": { poster: "/images/video-posters/raz-showreel.webp", duration: "PT8S" },
  "/videos/second-skin.mp4": { poster: "/images/video-posters/second-skin.webp", duration: "PT15S" },
}

export function posterFor(src: string): string | undefined {
  return VIDEO_ASSETS[src]?.poster
}

/** ISO 8601 length, for schema.org's `duration`. */
export function durationFor(src: string): string | undefined {
  return VIDEO_ASSETS[src]?.duration
}
